config/routes.rb
Rails.application.routes.draw do

  get 'manage/menu'

  get 'manage/category'

  get 'manage/item'

  # get 'user/index'

  # get 'user/login'

  # get 'user/logout'

  # get 'user/dashboard'

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  root :to => "manage#menu"

  #Menu Api Routing
  get '/menu/index', to: 'menus#index', as: 'menu_index'
  delete '/menu/destroy', to: 'menus#destroy', as: 'menu_destroy'
  post '/menu/create', to: 'menus#create', as: 'menu_create'
  put '/menu/update', to: 'menus#update', as: 'menu_update'

  #Category Api Routing
  delete '/category/destroy', to: 'category#destroy', as: 'category_destroy'
  post '/category/create', to: 'category#create', as: 'category_create'
  put '/category/update', to: 'category#update', as: 'category_update'
  get '/category/categorybymenu/:id', to: 'category#categorybymenu', as: 'categorybymenu'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true
end

app/models/menu.rb
class Menu < ApplicationRecord
  # validates :name , presence_of: true
  # attr_accessor :name

  validates :name, presence: true, uniqueness: true, length: { maximum: 100 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	# before_action :require_login

	# private

	# def require_login
	# 	unless session[:current_user_bid]?
	# 	  flash[:error] = "You must be logged in to access this section"
	# 	  redirect_to new_login_url # halts request cycle
	# 	end
	# end
	
	def set_variables
		@color = 'yellow'
	end


end

app/controllers/category_controller.rb
class CategoryController < ApplicationController
  protect_from_forgery :except => [:destroy, :update, :create]

  def categorybymenu  	
    @category = Category.where(menuid: params[:id])
    render json: @category  	
  end

  def create
    if request.post?
      Category.create(:name=> params[:name], :menuid=> params[:menuid])
    end
  end

  def update
    if request.put?
      Category.update(params[:id] , :name=> params[:name])  
      render json: { status: :ok}
    end
  end

  def destroy
    if request.delete?     
        @status_update = Category.where(id: params[:id])
        if @status_update.present?
           Category.destroy(params[:id])
        end
    end    
  end

end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
  	render(:status => 404)
  end

  def internal_server_error
  	render(:status => 500)
  end
end

app/controllers/manage_controller.rb
class ManageController < ApplicationController
  def menu
    session[:business_id] = 1
  end

  def category
    session[:business_id] = 1
    @category = Menu.all
  end

  def item
    session[:business_id] = 1
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  protect_from_forgery :except => [:destroy, :update, :create]

  def index
    @menus = Menu.where(restid: session[:business_id])
    render json: @menus
  end

  def create
    if request.post?
      menu = Menu.create(:name=> params[:name], :restid=> session[:business_id])
      if menu.save

      else
        puts menu.errors.messages
        render json: menu.errors.messages
      end
    end
  end

  def update
    if request.put?
      @menu = Menu.update(params[:id] , :name=> params[:name])
      if @menu.valid?
        render json: { status: :ok}
      else
        render json: @menu.errors.messages
      end
    end
  end

  def destroy
    if request.delete?
      @status_update = Menu.where(id: params[:id])
      if @status_update.present?
        Menu.destroy(params[:id])
      else
        @status_update.errors.messages
      end
    end
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController

  before_action :set_variables
  require "base64"

  def index
    
  end

  def login

    # if session[:current_user_bid] :
    #   redirect_to user_dashboard_path

    @skip_footer = true
    @skip_header = true 
    @skip_menu = true       
    # if request.post?
    #   result = Device.where("business_id = ? AND passcode = ?", params[:soid],params[:passcode]).count

    #   return get device id, soid 
    #   session[:current_user_bid] = soid
    #   base_auth = Base64.encode64('Send reinforcements')
    #   session[:base_auth] = base_auth

      
    #   # Device.find_by(business_id: params[:soid], passcode: ,params[:passcode]).attributes.slice('business_id', 'device_id')
    #   if result!=0
        
    #   end
    # end
  end

  def logout    
    session[:current_user_bid] = nil
    session[:base_auth] = nil
    redirect_to user_login_path
  end

  def dashboard
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/manage_helper.rb
module ManageHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/views/layouts/_footer.html.erb
<footer class="main-footer">
 	<div class="pull-right hidden-xs">
	  <b>Version</b> 0.1
	</div>
	<strong>Copyright &copy; 2017-2018 <a href="http://shopowner.in/">ShopOwner</a>.</strong>
	ShopOwner is a product of <a href="http://www.datamattic.com" target="_blank"><strong>Datamattic Inc</strong>.</a>
	All rights reserved.
</footer>

app/views/layouts/_header.html.erb
  <header class="main-header">
    <!-- Logo -->
    <a href="index2.html" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>SO</b></span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>ShopOwner</b> POS</span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>

      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">

          <li class="dropdown notifications-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-bell-o"></i>
              <!-- <span class="label label-warning">10</span> -->
            </a>
            <ul class="dropdown-menu">
              <li class="header">No notification</li>
            </ul>
          </li>
          <!-- Tasks: style can be found in dropdown.less -->
        
          <!-- User Account: style can be found in dropdown.less -->
          <li class="dropdown user user-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <span class="hidden-xs">Alexander Pierce</span>
            </a>
            <ul class="dropdown-menu">
              <!-- User image -->
              <li class="user-header">
                <img src="dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">

                <p>
                  Alexander Pierce - Web Developer
                </p>
              </li>
              <!-- Menu Footer-->
              <li class="user-footer">
                <div class="pull-left">
                  <a href="#" class="btn btn-default btn-flat">Profile</a>
                </div>
                <div class="pull-right">
                  <a href="<%= user_logout_path %>" class="btn btn-default btn-flat">Sign out</a>
                </div>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </nav>
  </header>

app/views/layouts/_menu.html.erb
  <aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
      <!-- Sidebar user panel -->
      <div class="user-panel">
        <div class="pull-left image">
          <img src="<%= image_path('logo.png') %>" class="img-circle" alt="User Image">
        </div>
        <div class="pull-left info">
          <p>Back Office</p>          
          <span class="poweredby">Powered by Datamattic Inc.</span>          
        </div>
      </div>
      <!-- sidebar menu: : style can be found in sidebar.less -->
      <ul class="sidebar-menu">
        <li>
          <a href="<%= user_dashboard_path %>">
            <i class="fa fa-dashboard"></i> <span>Dashboard</span>
          </a>
        </li>
        <li>
          <a href="<%= menu_index_path %>">
            <i class="fa fa-bars"></i> <span>Menu</span>
          </a>
        </li>
        <!-- <li class="treeview">
          <a href="#">
            <i class="fa fa-files-o"></i>
            <span>Layout Options</span>
            <span class="pull-right-container">
              <span class="label label-primary pull-right">4</span>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="pages/layout/top-nav.html"><i class="fa fa-circle-o"></i> Top Navigation</a></li>
            <li><a href="pages/layout/boxed.html"><i class="fa fa-circle-o"></i> Boxed</a></li>
            <li><a href="pages/layout/fixed.html"><i class="fa fa-circle-o"></i> Fixed</a></li>
            <li><a href="pages/layout/collapsed-sidebar.html"><i class="fa fa-circle-o"></i> Collapsed Sidebar</a></li>
          </ul>
        </li>
        <li>
          <a href="pages/widgets.html">
            <i class="fa fa-th"></i> <span>Widgets</span>
            <span class="pull-right-container">
              <small class="label pull-right bg-green">new</small>
            </span>
          </a>
        </li>
        <li class="header">LABELS</li>
        <li><a href="#"><i class="fa fa-circle-o text-red"></i> <span>Important</span></a></li> -->
      </ul>
    </section>
    <!-- /.sidebar -->
  </aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <style type="text/css">
      .modal {
        text-align: center;
        padding: 0!important;
      }
      
      .modal:before {
        content: '';
        display: inline-block;
        height: 100%;
        vertical-align: middle;
        margin-right: -4px;
      }
      
      .modal-dialog {
        display: inline-block;
        text-align: left;
        vertical-align: middle;
      }
    </style>
  </head>
  <body class="hold-transition skin-<%=@color%> sidebar-mini">
    <% unless @skip_menu %>
      <div class="wrapper">
        <div class="content-wrapper">
          <%= yield %>
        </div>
      </div>
    <% else %>
      <%= yield %>
    <% end %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript">
      $(document).ready(function() {
      
          function Callback(data)
          {
            $("ul").empty();
            $.each(data, function(index){
              var remove, edit;
              remove = '<a href="javascript:void(0);" class="remove" remove-id ="'+data[index].id+'">Remove</a>'
              edit = '<button type="button" data-toggle="modal" data-target="#edit'+data[index].id+'">Edit</button>'
              edit_modal = '<div class="modal fade" id="edit'+data[index].id+'" role="dialog"><div class="modal-dialog"><div class="modal-content"><form id="editform'+data[index].id+'" action=""><div class="modal-header"><button type="button" class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Edit Brand</h4></div><div class="modal-body"><input type="text" name="name" class="floating-item-input input-item" value="'+data[index].name+'" /><div class="error-row"></div></div><div class="modal-footer"><button type="button" class="btn btn-default modalclose" data-dismiss="modal">Close</button><input type="reset" name="Reset" class="btn btn-primary" value="Reset" /><input type="button" name="" class="btn btn-primary edit" edit-id="'+data[index].id+'" value="Save changes" /></div></form</div></div></div>';
              $(".load_data ul").append("<li> id: " + data[index].id + "----name: " + data[index].name + remove + edit +"</li>"+edit_modal+"");
            });
          }
      
      
          function callApiService(requestUrl,type,data=false,callbackfn=false,this_var=false,redirect_url=false) {
            if(this_var)
              var this_var = $(this_var);
      
            $.ajax({
                type: type,
                url: requestUrl,
                data: data,
                "headers": {
                  "content-type": "application/json",
                },
                success: function (response) {
           // x = JSON.stringify(response);
         //         alert(x);
      
                    if(type=='DELETE')
                      this_var.parents('li').remove();
      
      
                    if(type=='GET')
                        callbackfn(response)
      
                    if(type=='POST'){
                      if(redirect_url&&callbackfn){
                          setTimeout(function(){
                              callApiService(redirect_url,'GET','',callbackfn,this);
                                for (var key in response) {
                                  $('#err').addClass('.error-row').css('display', 'block').text(key + ' : ' + response[key]);
                                }
                              $('.close').trigger( "click" );
                          }, 500);
                      }else if(callbackfn){
                        callbackfn(response);
                        $('.close').trigger( "click" );
                      }
                    }
      
                    if(type=='PUT'){
                      if(redirect_url&&callbackfn){
                          setTimeout(function(){
                              callApiService(redirect_url,'GET','',callbackfn,this);
                                for (var key in response) {
                                  $('#err').addClass('.error-row').css('display', 'block').text(key + ' : ' + response[key]);
                                }
                              $('.modal-backdrop').hide();
                          }, 500);
                      }else if(callbackfn){
                        callbackfn(response);
                        $('.modal-backdrop').hide();
                      }
                    }
                },
                error: function (response) {
                    return 'error'
                }
            });
          }
      
          $('.modal').on('hidden.bs.modal', function () {
              $(this).find('form').trigger('reset');
          });
      
          $('.close').click(function(){
            $('.modal').modal('hide');
          });
      
          function triggerChangeEvent(data) {
            $(".menudropdown").trigger('change');
          }
      
          function dropDownCallback(data) {
            $("select").empty();
      
            $(".load_data select").append('<option value="">Choose Option</option>');
      
            $.each(data, function(index){
              $(".load_data select").append("<option value='" + data[index].id + "'>" + data[index].name + "</option>");
            });
          }
      
          $(".menudropdown").change(function () {
            var menuid = this.value;
            var requestUrl = "<%= categorybymenu_path(id: 'device_id') %>";
            requestUrl = requestUrl.replace('device_id',menuid);
            if(menuid)
              callApiService(requestUrl,"GET",'',Callback);
          });
      
      
      
          <%= yield :js %>
      
      
      });
    </script>
  </body>
</html>

app/views/menus/_form.html.erb
<%= form_for(menu) do |f| %>
  <% if menu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(menu.errors.count, "error") %> prohibited this menu from being saved:</h2>
      <ul>
        <% menu.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/menus/edit.html.erb
<h1>Editing Menu</h1>

<%= render 'form', menu: @menu %>

<%= link_to 'Show', @menu %> |
<%= link_to 'Back', menus_path %>

app/views/menus/index.html.erb
<p id="notice"><%= notice %></p>
<h1>brands</h1>
<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @menus.each do |menu| %>
      <% @menus.erros.messages %>
      <tr>
        <td><%= menu.name %> - <%= menu.id %></td>
        <td><%= link_to 'Edit', edit_menu_path(menu) %></td>
        <td><%= link_to 'Destroy', menu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Menu', new_menu_path %>

app/views/menus/new.html.erb
<h1>New Menu</h1>

<%= render 'form', menu: @menu %>

<%= link_to 'Back', menus_path %>

app/views/menus/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_menu_path(@menu) %> |
<%= link_to 'Back', menus_path %>

app/views/user/dashboard.html.erb
<h1>User#dashboard</h1>
<p>Find me in app/views/user/dashboard.html.erb</p>

app/views/user/index.html.erb
<h1>User#index</h1>
<p>Find me in app/views/user/index.html.erb</p>

app/views/user/login.html.erb
<div class="container">
	<div class="login-container">
            <div id="output"></div>
            <div class="avatar"></div>
            <div class="logindesc"> <b> ShopOwner | Backoffice </b></div>
            <div class="form-box">
                <form  method="post" id="loginForm" action="<%= user_login_path %>" onsubmit="return loginValidation();">
                    <input name="soid" type="number" placeholder="ShopOwner ID">
                    <input type="passcode" name="passcode" placeholder="Passcode">
                    <button class="btn btn-block login" type="submit">Login</button>
                </form>
            </div>
        </div>
        
</div>